import type { Metadata } from "next";
import Header from "./_layout-components/Header/Header";
import Footer from "./_layout-components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header/>
      {children}
      <Footer/>
    </>
  );
}
